# File: ingest/config/export_profiles.yml
map:
  path: site/static/data/markets.map.json
  fields:
    - listing_id
    - listing_name
    - organization
    - street
    - longitude
    - latitude
    - full_address
    - city
    - state
    - zip
    - zip_lat
    - zip_lon
    - location_desc
    - listing_desc
    - snap_acceptance
    - program_snap
    - snap_central_booth
    - snap_vendor_pos

search:
  path: site/static/data/markets.search.json
  fields:
    - listing_id
    - listing_name
    - organization
    - street
    - city
    - state
    - zip
    - full_address
    - longitude
    - latitude
    - zip_lat
    - zip_lon
    - program_snap
    - program_wic
    - program_wic_fmnp
    - program_senior_fmnp
    - program_incentives
    - snap_central_booth
    - snap_vendor_pos
    - snap_acceptance
    - search_city
    - search_state
    - search_zip
    - search_haystack

full:
  path: data/processed/markets.full.parquet
  fields: ["*"]
