# File: ingest/config/mapping_programs.yml
fnap_flags:
  FNAP_1: program_wic
  FNAP_2: program_snap
  FNAP_3: program_incentives
  FNAP_4: program_wic_fmnp
  FNAP_5: program_senior_fmnp

text_fields:
  programs_raw: FNAP
  program_incentives_desc: FNAP_3_desc

snap:
  option_text: SNAP_option
  central_booth_flag: SNAP_option_1
  vendor_pos_flag: SNAP_option_2
