# File: ingest/config/schema.yml
required:
  - listing_id
  - listing_name
  - location_address
  - location_x
  - location_y

rename:
  location_x: longitude
  location_y: latitude
  orgnization: organization

dtypes:
  listing_id: str
  update_time: datetime
  listing_name: str
  location_address: str
  longitude: float
  latitude: float
  city: str
  state: str
  zip: str
  organization: str
  SNAP_option: str
  SNAP_option_1: bool
  SNAP_option_2: bool
  FNAP: str
  FNAP_1: bool
  FNAP_2: bool
  FNAP_3: bool
  FNAP_4: bool
  FNAP_5: bool
  FNAP_3_desc: str
