baseURL = "https://www.freshlocalharvest.org"
languageCode = "en-us"
title = "Fresh Local Harvest"
theme = "ananke"
enableRobotsTXT = true
canonifyURLs = false  # keep relative URLs in dev; we'll set a real baseURL in prod

[pagination]
  pagerSize = 10      # replaces deprecated 'paginate'

[params]
  description = "Find fresh local produce and farmers markets—fast."
  env = "development" # used later to gate dev-only API status widget
  customCSS = ["css/typography.css"]
  background_color_class = "bg-hero-green"
  site_logo = "images/logo-pin.webp"   # path is relative to /static


[menus]
  [[menu.main]]
    name = "Home"
    pageRef = "/"
    weight = 10
  [[menu.main]]
    name = "Blog"
    pageRef = "/posts"
    weight = 20
  [[menu.main]]
    name = "Map"
    url = "/map/"
    weight = 20


[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[permalinks]
  posts = "/posts/:slug/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
