name: Update markets data

on:
  schedule:
    - cron: "30 13 * * *"   # 09:30 Eastern daily (test time)
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install "httpx[http2]"

      - name: Export data from USDA Local Food Portal
        env:
          USDA_API_KEY: ${{ secrets.USDA_API_KEY }}
        run: python scripts/export_markets.py

      - name: Verify markets.json has items
        run: >
          python -c "import json,sys,pathlib;
          p=pathlib.Path('site/static/data/markets.json');
          d=json.loads(p.read_text(encoding='utf-8'));
          n=(len(d) if isinstance(d,list) else
             (len(d.get('items',[])) if isinstance(d,dict) else 0));
          print('items_count=',n);
          sys.exit(0 if n>0 else 1)"

      - name: Commit updated markets.json (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add site/static/data/markets.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore(data): update markets.json"
            git push
          fi

      - name: Upload markets.db artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: markets-db
          path: db/markets.db
          if-no-files-found: ignore
